build:
  environment:
    php: '7.1'
    mysql: '5.7'
    hosts:
        laravel.dev: '127.0.0.1'
    variables:
        APP_KEY: 'base64:OYl4Bk9ekouOUIRXyeTD0FVi+cJ9D+HMyDJBgSBSUuI='
        APP_ENV: 'testing'
        APP_URL: 'http://laravel.dev'
        API_HOST: 'laravel.dev'
        DB_HOST: '127.0.0.1'
        DB_DATABASE: 'scrutinizer'
        DB_USERNAME: 'root'
        DB_PASSWORD: ''
  dependencies:
    before:
      - mysql -u root -e 'CREATE DATABASE testing'
